server:
  port: 8585

spring:
  liquibase:
    enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:h2:mem:spring-security
    driver-class-name: org.h2.Driver
    username: root
    password: 12345

jwt:
  token:
    signing:
      key: open-weather

open:
  weather:
    url: https://api.openweathermap.org
    version: /data/3.0
    ext: /onecall
    api-key: ask_me_or_get_own_from_openweathermap.org
