server:
  port: 8585
spring:
  liquibase:
    enabled: true
  jpa:
    database-platform:
    hibernate:
      ddl-auto: none
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres?schema=open_weather
    name: open_weather
    username: open_weather
    password: 123123weather
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jwt:
  token:
    signing:
      key: open-weather

open:
  weather:
    url: https://api.openweathermap.org
    version: /data/3.0
    ext: /onecall
    api-key: ask_me_or_get_own_from_openweathermap.org

springdoc:
  swagger-ui:
      defaultModelsExpandDepth: 1
      showExtensions: false