server:
  port: 8585
spring:
  liquibase:
    enabled: true
  jpa:
    database-platform:
    hibernate:
      ddl-auto: none
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres?schema=open_weather
    name: open_weather
    username: open_weather
    password: 123123weather
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    uz: INFO
  file:
    path: log/
    name: log/open_weather.log
  level.uz:
    paynet: INFO
  pattern:
    dateformat: [dd MM yyyy HH:mm:ss,SSS]
    file: "[%d{dd-MM-yyyy HH:mm:ss:ss,SSS}] [%thread] %-5level %logger{36} - %msg%n"
jwt:
  token:
    signing:
      key: open-weather

open:
  weather:
    url: https://api.openweathermap.org
    version: /data/3.0
    ext: /onecall
    api-key: ask_me_or_get_own_from_openweathermap.org

springdoc:
  swagger-ui:
    defaultModelsExpandDepth: 1
    showExtensions: false