version: '1'

services:
  open-weather-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8585:8585
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=open_weather
      - POSTGRES_USER=open_weather
      - POSTGRES_PASSWORD=123123weather
